### PR TITLE
multi-targetting net461 and netstandard 2.0 to support VS2015

### PR DESCRIPTION
**Pull request by HEskandari**
Connects to https://github.com/Particular/PlatformDevelopment/issues/2151

### CODE REVIEW

**Comment by mauroservienti** [comment]
@Particular/nservicebus-maintainers can you take a look and confirm this is good to go?
We think it should be released as a minor, shall we take care of the release or there's a dedicated process?

**Comment by timbussmann** [comment]
I've pushed a change directly to this PR to update the approval tests to work better with the multitargeted assembly.

**Comment by HEskandari** [comment]
@timbussmann reviewed that bit. LGTM but can't approve my own PR.

**Comment by timbussmann** [comment]
> We think it should be released as a minor, shall we take care of the release or there's a dedicated process?

@mauroservienti yes, releasing the minor version would be responsibility of the task force.

**Pull request merged**
